"""create category and subscription tables

Revision ID: 3b68331321c9
Revises: cc886154104f
Create Date: 2023-09-24 20:02:22.319584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b68331321c9'
down_revision = 'cc886154104f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('valid_from', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'subscription_type', ['subscription_type_id'], ['id'])

    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_type_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('removed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('removed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('subscription_type_name')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('subscription_type_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
