"""create email tables

Revision ID: 4557567f666f
Revises: b5c997418880
Create Date: 2023-09-24 19:55:19.020417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4557567f666f'
down_revision = 'b5c997418880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'email_address', ['email_id'], ['id'])
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_email', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('removed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
