"""add cost to sub types

Revision ID: a5312ffe0c03
Revises: d13cbbd91cb1
Create Date: 2023-10-01 12:00:23.721570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5312ffe0c03'
down_revision = 'd13cbbd91cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
