"""create phone_nr and device tables

Revision ID: cc886154104f
Revises: 4557567f666f
Create Date: 2023-09-24 19:57:58.084477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc886154104f'
down_revision = '4557567f666f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('device_sn', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'])

    with op.batch_alter_table('user_phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'phone_number', ['phone_id'], ['id'])
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_phone', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('removed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('phone_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('removed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('device_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('device_sn')
        batch_op.drop_column('device_name')

    # ### end Alembic commands ###
