"""add months var in subscription types

Revision ID: d13cbbd91cb1
Revises: 3b68331321c9
Create Date: 2023-10-01 11:47:41.039687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13cbbd91cb1'
down_revision = '3b68331321c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('months', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_type', schema=None) as batch_op:
        batch_op.drop_column('months')

    # ### end Alembic commands ###
